# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 16:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170802_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
